"""Persistence ports for the Merchant service."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from merchant.domain.entities import (
    LabelStockAllocation,
    Merchant,
    MerchantApplication,
    PrinterAuthorization,
    Product,
    ProductCategory,
    StandingShipmentPolicy,
    Store,
    TeamMembership,
)
from merchant.domain.messaging import InboxRecord, OutboxRecord


class ApplicationRepository(Protocol):
    def save(self, application: MerchantApplication) -> None: ...

    def get(self, application_id: UUID) -> MerchantApplication | None: ...

    def find_open_for_applicant(self, principal_id: UUID) -> MerchantApplication | None: ...

    def list_for_applicant(self, principal_id: UUID) -> tuple[MerchantApplication, ...]: ...

    def find_by_reference(self, reference: str) -> MerchantApplication | None: ...


class MerchantRepository(Protocol):
    def save(self, merchant: Merchant) -> None: ...

    def get(self, merchant_id: UUID) -> Merchant | None: ...

    def find_by_code(self, merchant_code: str) -> Merchant | None: ...

    def find_by_owner(self, principal_id: UUID) -> Merchant | None: ...

    def list_for_owner(self, principal_id: UUID) -> tuple[Merchant, ...]: ...


class PolicyRepository(Protocol):
    def save(self, policy: StandingShipmentPolicy) -> None: ...

    def get(self, merchant_id: UUID) -> StandingShipmentPolicy | None: ...


class StoreRepository(Protocol):
    def save(self, store: Store) -> None: ...

    def get(self, store_id: UUID) -> Store | None: ...

    def list_for_merchant(
        self, merchant_id: UUID, *, include_archived: bool = False
    ) -> tuple[Store, ...]: ...

    def find_default_pickup(self, merchant_id: UUID) -> Store | None: ...


class MembershipRepository(Protocol):
    def save(self, membership: TeamMembership) -> None: ...

    def get(self, membership_id: UUID) -> TeamMembership | None: ...

    def list_for_merchant(self, merchant_id: UUID) -> tuple[TeamMembership, ...]: ...

    def list_for_principal(self, principal_id: UUID) -> tuple[TeamMembership, ...]: ...

    def find_live_for_phone(
        self, merchant_id: UUID, phone: str
    ) -> TeamMembership | None: ...

    def list_pending_for_phone(self, phone: str) -> tuple[TeamMembership, ...]: ...


class LabelStockRepository(Protocol):
    def save(self, allocation: LabelStockAllocation) -> None: ...

    def get(self, allocation_id: UUID) -> LabelStockAllocation | None: ...

    def list_for_merchant(self, merchant_id: UUID) -> tuple[LabelStockAllocation, ...]: ...


class PrinterAuthorizationRepository(Protocol):
    def save(self, authorization: PrinterAuthorization) -> None: ...

    def get(self, authorization_id: UUID) -> PrinterAuthorization | None: ...

    def list_for_merchant(self, merchant_id: UUID) -> tuple[PrinterAuthorization, ...]: ...


class CatalogueRepository(Protocol):
    def save_product(self, product: Product) -> None: ...

    def get_product(self, product_id: UUID) -> Product | None: ...

    def list_products(
        self, merchant_id: UUID, *, category_id: UUID | None = None
    ) -> tuple[Product, ...]: ...

    def save_category(self, category: ProductCategory) -> None: ...

    def get_category(self, category_id: UUID) -> ProductCategory | None: ...

    def list_categories(self, merchant_id: UUID) -> tuple[ProductCategory, ...]: ...

    def count_products_in_category(self, category_id: UUID) -> int: ...


class OutboxRepository(Protocol):
    def insert(self, record: OutboxRecord) -> None: ...

    def get_by_event_id(self, event_id: UUID) -> OutboxRecord | None: ...

    def list_pending(self) -> tuple[OutboxRecord, ...]: ...

    def list_for_aggregate(self, aggregate_id: UUID) -> tuple[OutboxRecord, ...]: ...


class InboxRepository(Protocol):
    def find(self, consumer_name: str, event_id: UUID) -> InboxRecord | None: ...

    def insert(self, record: InboxRecord) -> None: ...

    def save(self, record: InboxRecord) -> None: ...


class MerchantUnitOfWork(Protocol):
    @property
    def applications(self) -> ApplicationRepository: ...

    @property
    def merchants(self) -> MerchantRepository: ...

    @property
    def policies(self) -> PolicyRepository: ...

    @property
    def stores(self) -> StoreRepository: ...

    @property
    def memberships(self) -> MembershipRepository: ...

    @property
    def label_stock(self) -> LabelStockRepository: ...

    @property
    def printer_authorizations(self) -> PrinterAuthorizationRepository: ...

    @property
    def catalogue(self) -> CatalogueRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    @property
    def inbox(self) -> InboxRepository: ...

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
