"""Persistence ports for the Workforce service.

There is no outbox port. Workforce answers questions — is this driver assignable? — over
HTTP, and publishes no integration events of its own.
"""

from __future__ import annotations

from datetime import date
from typing import Protocol
from uuid import UUID

from workforce.domain.entities import (
    AttendanceRecord,
    DriverApplication,
    DriverProfile,
    LatenessBlock,
    LeaveRequest,
    ShiftPattern,
)
from workforce.domain.messaging import InboxRecord


class ApplicationRepository(Protocol):
    def save(self, application: DriverApplication) -> None: ...

    def get(self, application_id: UUID) -> DriverApplication | None: ...

    def find_open_for_principal(self, principal_id: UUID) -> DriverApplication | None: ...

    def find_by_reference(self, reference: str) -> DriverApplication | None: ...


class DriverRepository(Protocol):
    def save(self, driver: DriverProfile) -> None: ...

    def get(self, driver_id: UUID) -> DriverProfile | None: ...

    def find_by_principal(self, principal_id: UUID) -> DriverProfile | None: ...


class ShiftPatternRepository(Protocol):
    def save(self, pattern: ShiftPattern) -> None: ...

    def current_for(self, driver_id: UUID, day: date) -> ShiftPattern | None: ...

    def list_for_driver(self, driver_id: UUID) -> tuple[ShiftPattern, ...]: ...


class AttendanceRepository(Protocol):
    def save(self, record: AttendanceRecord) -> None: ...

    def find(self, driver_id: UUID, shift_date: date) -> AttendanceRecord | None: ...

    def list_for_driver(self, driver_id: UUID) -> tuple[AttendanceRecord, ...]: ...


class BlockRepository(Protocol):
    def save(self, block: LatenessBlock) -> None: ...

    def get(self, block_id: UUID) -> LatenessBlock | None: ...

    def find_active(self, driver_id: UUID) -> LatenessBlock | None: ...

    def list_active(self) -> tuple[LatenessBlock, ...]: ...


class LeaveRepository(Protocol):
    def save(self, request: LeaveRequest) -> None: ...

    def get(self, leave_id: UUID) -> LeaveRequest | None: ...

    def list_for_driver(self, driver_id: UUID) -> tuple[LeaveRequest, ...]: ...

    def list_pending(self) -> tuple[LeaveRequest, ...]: ...

    def find_covering(self, driver_id: UUID, day: date) -> LeaveRequest | None: ...


class InboxRepository(Protocol):
    def find(self, consumer_name: str, event_id: UUID) -> InboxRecord | None: ...

    def insert(self, record: InboxRecord) -> None: ...

    def save(self, record: InboxRecord) -> None: ...


class WorkforceUnitOfWork(Protocol):
    @property
    def applications(self) -> ApplicationRepository: ...

    @property
    def drivers(self) -> DriverRepository: ...

    @property
    def patterns(self) -> ShiftPatternRepository: ...

    @property
    def attendance(self) -> AttendanceRepository: ...

    @property
    def blocks(self) -> BlockRepository: ...

    @property
    def leave(self) -> LeaveRepository: ...

    @property
    def inbox(self) -> InboxRepository: ...

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
