"""Persistence ports for the Ordering service."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ordering.domain.entities import (
    GoodsCategory,
    Order,
    ShipmentRequest,
    TariffRate,
)
from ordering.domain.messaging import InboxRecord, OutboxRecord


class OrderRepository(Protocol):
    def save(self, order: Order) -> None: ...

    def get(self, order_id: UUID) -> Order | None: ...

    def list_for_principal(self, principal_id: UUID) -> tuple[Order, ...]: ...


class ShipmentRequestRepository(Protocol):
    def save(self, request: ShipmentRequest) -> None: ...

    def get(self, request_id: UUID) -> ShipmentRequest | None: ...

    def find_by_tracking_code(self, tracking_code: str) -> ShipmentRequest | None: ...

    def find_by_label_code(self, label_code: str) -> ShipmentRequest | None: ...

    def list_for_order(self, order_id: UUID) -> tuple[ShipmentRequest, ...]: ...

    def list_for_principal(self, principal_id: UUID) -> tuple[ShipmentRequest, ...]: ...

    def list_for_merchant(self, merchant_id: UUID) -> tuple[ShipmentRequest, ...]: ...


class GoodsCatalogueRepository(Protocol):
    def save(self, category: GoodsCategory) -> None: ...

    def get(self, code: str) -> GoodsCategory | None: ...

    def list_active(self) -> tuple[GoodsCategory, ...]: ...


class TariffRepository(Protocol):
    def save(self, rate: TariffRate) -> None: ...

    def find_rate(
        self, *, origin: str, destination: str, moment: datetime
    ) -> TariffRate | None: ...

    def list_rates(self) -> tuple[TariffRate, ...]: ...


class OutboxRepository(Protocol):
    def insert(self, record: OutboxRecord) -> None: ...

    def get_by_event_id(self, event_id: UUID) -> OutboxRecord | None: ...

    def list_pending(self) -> tuple[OutboxRecord, ...]: ...

    def list_for_aggregate(self, aggregate_id: UUID) -> tuple[OutboxRecord, ...]: ...


class InboxRepository(Protocol):
    def find(self, consumer_name: str, event_id: UUID) -> InboxRecord | None: ...

    def insert(self, record: InboxRecord) -> None: ...

    def save(self, record: InboxRecord) -> None: ...


class OrderingUnitOfWork(Protocol):
    @property
    def orders(self) -> OrderRepository: ...

    @property
    def requests(self) -> ShipmentRequestRepository: ...

    @property
    def goods(self) -> GoodsCatalogueRepository: ...

    @property
    def tariffs(self) -> TariffRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    @property
    def inbox(self) -> InboxRepository: ...

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
