"""Persistence ports for the Claims service."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from claims.domain.entities import ClaimMessage, CompensationClaim, DriverIncident
from claims.domain.messaging import InboxRecord, OutboxRecord


class ClaimRepository(Protocol):
    def save(self, claim: CompensationClaim) -> None: ...

    def get(self, claim_id: UUID) -> CompensationClaim | None: ...

    def find_by_reference(self, reference: str) -> CompensationClaim | None: ...

    def find_open_for_parcel(self, tracking_code: str) -> CompensationClaim | None: ...

    def list_for_parcel(self, tracking_code: str) -> tuple[CompensationClaim, ...]: ...

    def list_for_principal(self, principal_id: UUID) -> tuple[CompensationClaim, ...]: ...

    def list_awaiting_operations(self) -> tuple[CompensationClaim, ...]: ...

    def list_for_operations_view(
        self, limit: int = 200
    ) -> tuple[CompensationClaim, ...]: ...

    def next_sequence_for_day(self, day: str) -> int: ...


class MessageRepository(Protocol):
    def save(self, message: ClaimMessage) -> None: ...

    def list_for_claim(self, claim_id: UUID) -> tuple[ClaimMessage, ...]: ...

    def count_for_claim(self, claim_id: UUID) -> int: ...


class IncidentRepository(Protocol):
    def save(self, incident: DriverIncident) -> None: ...

    def get(self, incident_id: UUID) -> DriverIncident | None: ...

    def find_by_reference(self, reference: str) -> DriverIncident | None: ...

    def list_for_driver(self, driver_id: UUID) -> tuple[DriverIncident, ...]: ...

    def list_open(self) -> tuple[DriverIncident, ...]: ...

    def next_sequence_for_day(self, day: str) -> int: ...


class OutboxRepository(Protocol):
    def insert(self, record: OutboxRecord) -> None: ...

    def get_by_event_id(self, event_id: UUID) -> OutboxRecord | None: ...

    def list_pending(self) -> tuple[OutboxRecord, ...]: ...

    def list_for_aggregate(self, aggregate_id: UUID) -> tuple[OutboxRecord, ...]: ...


class InboxRepository(Protocol):
    def find(self, consumer_name: str, event_id: UUID) -> InboxRecord | None: ...

    def insert(self, record: InboxRecord) -> None: ...

    def save(self, record: InboxRecord) -> None: ...


class ClaimsUnitOfWork(Protocol):
    @property
    def claims(self) -> ClaimRepository: ...

    @property
    def messages(self) -> MessageRepository: ...

    @property
    def incidents(self) -> IncidentRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    @property
    def inbox(self) -> InboxRepository: ...

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
