"""Persistence ports for the Hub service."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from hub.domain.entities import (
    Consignment,
    DropOff,
    Hub,
    Linehaul,
    ParcelPresence,
    SealCheck,
    VehiclePosition,
)
from hub.domain.messaging import InboxRecord, OutboxRecord


class HubRepository(Protocol):
    def save(self, hub: Hub) -> None: ...

    def get(self, hub_id: UUID) -> Hub | None: ...

    def find_by_code(self, code: str) -> Hub | None: ...

    def list_all(self) -> tuple[Hub, ...]: ...


class DropOffRepository(Protocol):
    def save(self, drop_off: DropOff) -> None: ...

    def get(self, drop_off_id: UUID) -> DropOff | None: ...

    def find_by_tracking_code(self, tracking_code: str) -> DropOff | None: ...

    def find_by_label_code(self, label_code: str) -> DropOff | None: ...

    def list_open_for_hub(self, hub_id: UUID) -> tuple[DropOff, ...]: ...


class PresenceRepository(Protocol):
    def save(self, presence: ParcelPresence) -> None: ...

    def get(self, presence_id: UUID) -> ParcelPresence | None: ...

    def find_in_hub(self, hub_id: UUID, tracking_code: str) -> ParcelPresence | None: ...

    def list_for_hub(self, hub_id: UUID) -> tuple[ParcelPresence, ...]: ...

    def list_for_consignment(self, consignment_id: UUID) -> tuple[ParcelPresence, ...]: ...


class ConsignmentRepository(Protocol):
    def save(self, consignment: Consignment) -> None: ...

    def get(self, consignment_id: UUID) -> Consignment | None: ...

    def find_by_seal_code(self, seal_code: str) -> Consignment | None: ...

    def list_for_hub(self, hub_id: UUID) -> tuple[Consignment, ...]: ...


class SealCheckRepository(Protocol):
    def save(self, check: SealCheck) -> None: ...

    def list_for_consignment(self, consignment_id: UUID) -> tuple[SealCheck, ...]: ...


class LinehaulRepository(Protocol):
    def save(self, linehaul: Linehaul) -> None: ...

    def get(self, linehaul_id: UUID) -> Linehaul | None: ...

    def find_for_consignment(self, consignment_id: UUID) -> Linehaul | None: ...

    def list_for_hub(self, hub_id: UUID) -> tuple[Linehaul, ...]: ...


class PositionRepository(Protocol):
    def save(self, position: VehiclePosition) -> None: ...

    def list_for_linehaul(self, linehaul_id: UUID) -> tuple[VehiclePosition, ...]: ...


class OutboxRepository(Protocol):
    def insert(self, record: OutboxRecord) -> None: ...

    def get_by_event_id(self, event_id: UUID) -> OutboxRecord | None: ...

    def list_pending(self) -> tuple[OutboxRecord, ...]: ...

    def list_for_aggregate(self, aggregate_id: UUID) -> tuple[OutboxRecord, ...]: ...


class InboxRepository(Protocol):
    def find(self, consumer_name: str, event_id: UUID) -> InboxRecord | None: ...

    def insert(self, record: InboxRecord) -> None: ...

    def save(self, record: InboxRecord) -> None: ...


class HubUnitOfWork(Protocol):
    @property
    def hubs(self) -> HubRepository: ...

    @property
    def drop_offs(self) -> DropOffRepository: ...

    @property
    def presences(self) -> PresenceRepository: ...

    @property
    def consignments(self) -> ConsignmentRepository: ...

    @property
    def seal_checks(self) -> SealCheckRepository: ...

    @property
    def linehauls(self) -> LinehaulRepository: ...

    @property
    def positions(self) -> PositionRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    @property
    def inbox(self) -> InboxRepository: ...

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
