"""Persistence ports for the Delivery service."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from delivery.domain.entities import (
    CourierRating,
    DeliveryManifest,
    DeliveryStop,
    FailedAttempt,
    ParcelIssueReport,
    PaymentRecord,
    PhotoEvidence,
    ReceiverPreference,
    VerificationAttempt,
)
from delivery.domain.messaging import InboxRecord, OutboxRecord


class ManifestRepository(Protocol):
    def save(self, manifest: DeliveryManifest) -> None: ...

    def get(self, manifest_id: UUID) -> DeliveryManifest | None: ...

    def find_open_for_driver(self, driver_principal_id: UUID) -> DeliveryManifest | None: ...


class StopRepository(Protocol):
    def save(self, stop: DeliveryStop) -> None: ...

    def get(self, stop_id: UUID) -> DeliveryStop | None: ...

    def find_by_tracking_code(self, tracking_code: str) -> DeliveryStop | None: ...

    def find_live_by_tracking_code(self, tracking_code: str) -> DeliveryStop | None: ...

    def list_for_manifest(self, manifest_id: UUID) -> tuple[DeliveryStop, ...]: ...

    def list_for_driver(self, driver_principal_id: UUID) -> tuple[DeliveryStop, ...]: ...


class VerificationRepository(Protocol):
    def save(self, attempt: VerificationAttempt) -> None: ...

    def list_for_stop(self, stop_id: UUID) -> tuple[VerificationAttempt, ...]: ...


class PaymentRepository(Protocol):
    def save(self, payment: PaymentRecord) -> None: ...

    def find_for_stop(self, stop_id: UUID) -> PaymentRecord | None: ...


class PhotoRepository(Protocol):
    def save(self, photo: PhotoEvidence) -> None: ...

    def list_for_stop(self, stop_id: UUID) -> tuple[PhotoEvidence, ...]: ...


class FailedAttemptRepository(Protocol):
    def save(self, attempt: FailedAttempt) -> None: ...

    def get(self, attempt_id: UUID) -> FailedAttempt | None: ...

    def list_awaiting_operations(self) -> tuple[FailedAttempt, ...]: ...

    def list_for_stop(self, stop_id: UUID) -> tuple[FailedAttempt, ...]: ...


class ReceiverRepository(Protocol):
    def save_preference(self, preference: ReceiverPreference) -> None: ...

    def find_preference(self, tracking_code: str) -> ReceiverPreference | None: ...

    def save_report(self, report: ParcelIssueReport) -> None: ...

    def list_reports(self, tracking_code: str) -> tuple[ParcelIssueReport, ...]: ...


class RatingRepository(Protocol):
    def save(self, rating: CourierRating) -> None: ...

    def find_for_tracking_code(self, tracking_code: str) -> CourierRating | None: ...

    def list_for_courier(self, courier_principal_id: UUID) -> tuple[CourierRating, ...]: ...


class OutboxRepository(Protocol):
    def insert(self, record: OutboxRecord) -> None: ...

    def get_by_event_id(self, event_id: UUID) -> OutboxRecord | None: ...

    def list_pending(self) -> tuple[OutboxRecord, ...]: ...

    def list_for_aggregate(self, aggregate_id: UUID) -> tuple[OutboxRecord, ...]: ...


class InboxRepository(Protocol):
    def find(self, consumer_name: str, event_id: UUID) -> InboxRecord | None: ...

    def insert(self, record: InboxRecord) -> None: ...

    def save(self, record: InboxRecord) -> None: ...


class DeliveryUnitOfWork(Protocol):
    @property
    def manifests(self) -> ManifestRepository: ...

    @property
    def stops(self) -> StopRepository: ...

    @property
    def verifications(self) -> VerificationRepository: ...

    @property
    def payments(self) -> PaymentRepository: ...

    @property
    def photos(self) -> PhotoRepository: ...

    @property
    def failed_attempts(self) -> FailedAttemptRepository: ...

    @property
    def receiver(self) -> ReceiverRepository: ...

    @property
    def ratings(self) -> RatingRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    @property
    def inbox(self) -> InboxRepository: ...

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
