"""Persistence ports for the Identity service."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from identity.domain.entities import OtpChallenge, Principal, RoleGrant, Session


class PrincipalRepository(Protocol):
    def save(self, principal: Principal) -> None: ...

    def get(self, principal_id: UUID) -> Principal | None: ...

    def find_by_phone_hash(self, phone_hash: str) -> Principal | None: ...


class OtpChallengeRepository(Protocol):
    def save(self, challenge: OtpChallenge) -> None: ...

    def get(self, challenge_id: UUID) -> OtpChallenge | None: ...

    def count_issued_since(self, phone_hash: str, since: datetime) -> int: ...

    def list_open_for_phone(self, phone_hash: str) -> tuple[OtpChallenge, ...]: ...


class SessionRepository(Protocol):
    def save(self, session: Session) -> None: ...

    def get(self, session_id: UUID) -> Session | None: ...

    def find_by_token_hash(self, token_hash: str) -> Session | None: ...

    def list_for_principal(self, principal_id: UUID) -> tuple[Session, ...]: ...


class RoleGrantRepository(Protocol):
    def save(self, grant: RoleGrant) -> None: ...

    def get(self, grant_id: UUID) -> RoleGrant | None: ...

    def list_for_principal(self, principal_id: UUID) -> tuple[RoleGrant, ...]: ...

    def find_active(
        self, principal_id: UUID, role: str, scope_id: UUID | None
    ) -> RoleGrant | None: ...


class IdentityUnitOfWork(Protocol):
    @property
    def principals(self) -> PrincipalRepository: ...

    @property
    def otp_challenges(self) -> OtpChallengeRepository: ...

    @property
    def sessions(self) -> SessionRepository: ...

    @property
    def role_grants(self) -> RoleGrantRepository: ...

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
